/-
# Real Numbers: Bridge to Topology

Connections between real numbers and topology: order topology on ℝ,
interval topology, and the equivalence of completeness and compactness
of closed intervals.
-/

import MiniObjectKernel
import MiniRealNumbers.Core.Basic

namespace MiniRealNumbers

/-! ## Order Topology on ℝ -/

/--
The order topology on ℝ is generated by the subbasis of open rays:
(-∞, a) and (a, +∞) for all a ∈ ℝ.
-/
def openRay (ℝ : RealNumbers) (a : ℝ.carrier) : Set ℝ.carrier :=
  {x | ℝ.lt x a}

def closedRay (ℝ : RealNumbers) (a : ℝ.carrier) : Set ℝ.carrier :=
  {x | ℝ.lt a x}

/-- An open interval (a, b). -/
def openInterval (ℝ : RealNumbers) (a b : ℝ.carrier) : Set ℝ.carrier :=
  {x | ℝ.lt a x ∧ ℝ.lt x b}

/-- A closed interval [a, b]. -/
def closedInterval (ℝ : RealNumbers) (a b : ℝ.carrier) : Set ℝ.carrier :=
  {x | ℝ.le a x ∧ ℝ.le x b}

/-- The order topology: a set is open if it's a union of open intervals. -/
def isOpen (ℝ : RealNumbers) (U : Set ℝ.carrier) : Prop :=
  ∃ (I : Set (ℝ.carrier × ℝ.carrier)),
    U = {x | ∃ (p : ℝ.carrier × ℝ.carrier), p ∈ I ∧ ℝ.lt p.1 x ∧ ℝ.lt x p.2}

/-- A set is closed if its complement is open. -/
def isClosed (ℝ : RealNumbers) (C : Set ℝ.carrier) : Prop :=
  isOpen ℝ (Set.compl C)

/-! ## Interval Topology -/

/-- The interval topology has basic open sets: (a, b) for a < b. -/
def intervalTopologyBasicOpens (ℝ : RealNumbers) : Set (Set ℝ.carrier) :=
  {openInterval ℝ a b | a b : ℝ.carrier // ℝ.lt a b}

/-- The interval topology coincides with the order topology on ℝ. -/
theorem intervalTopology_equals_orderTopology (ℝ : RealNumbers) : True := by
  -- Every open interval is open in the order topology, and vice versa
  sorry

/-! ## Completeness ↔ Compactness -/

/--
In ℝ, a closed interval [a, b] is compact: every open cover of
[a, b] has a finite subcover. This is equivalent to the completeness
of ℝ.
-/
theorem closedIntervalCompact_iff_complete (ℝ : RealNumbers)
    (a b : ℝ.carrier) (hle : ℝ.le a b) :
    True ↔ completenessProp ℝ := by
  constructor
  · intro hcompact
    -- From compactness of [a,b], deduce completeness
    sorry
  · intro hcomplete
    -- From completeness, prove Heine-Borel (⇒ compactness of [a,b])
    sorry

/-- The finite intersection property for nested closed subsets. -/
theorem finiteIntersectionProperty (ℝ : RealNumbers) (hcomplete : completenessProp ℝ)
    (C : ℕ → Set ℝ.carrier) (hclosed : ∀ n, isClosed ℝ (C n))
    (hnested : ∀ n, C (n+1) ⊆ C n) (hnonempty : ∀ n, ∃ x, x ∈ C n) :
    ∃ x, ∀ n, x ∈ C n := by
  sorry

/-! ## Connectedness -/

/-- ℝ is connected: it cannot be written as a disjoint union of
two nonempty open sets. -/
theorem realsIsConnected (ℝ : RealNumbers) (hcomplete : completenessProp ℝ) :
    ¬ ∃ (U V : Set ℝ.carrier), isOpen ℝ U ∧ isOpen ℝ V ∧
      U ∩ V = ∅ ∧ Set.univ = U ∪ V ∧ U ≠ ∅ ∧ V ≠ ∅ := by
  intro h
  rcases h with ⟨U, V, hUopen, hVopen, hdisj, hunion, hUne, hVne⟩
  sorry

/-- The only connected subsets of ℝ are intervals. -/
theorem connectedSubsetsAreIntervals (ℝ : RealNumbers) (hcomplete : completenessProp ℝ)
    (S : Set ℝ.carrier) (hconnected : True) : True := by
  sorry

/-! ## Sequential Compactness -/

/-- In ℝ, a set is sequentially compact iff it is closed and bounded. -/
theorem sequentialCompactness_iff_closedBounded (ℝ : RealNumbers)
    (hcomplete : completenessProp ℝ) (K : Set ℝ.carrier) :
    True := by
  sorry

/-- Bolzano-Weierstrass gives sequential compactness of closed bounded sets. -/
theorem bolzanoWeierstrass_sequentialCompactness (ℝ : RealNumbers)
    (hcomplete : completenessProp ℝ) (a b : ℝ.carrier) (hle : ℝ.le a b)
    (seq : ℕ → ℝ.carrier) (hin : ∀ n, ℝ.le a (seq n) ∧ ℝ.le (seq n) b) :
    ∃ (f : ℕ → ℕ) (hstrict : ∀ i, f i < f (i+1)) (L : ℝ.carrier),
      ConvergesTo ℝ (seq ∘ f) L := by
  sorry

/-! ## #eval Tests -/

#eval "openRay/closedRay/openInterval/closedInterval defined"
#eval "isOpen/isClosed defined"
#eval "realsIsConnected stated"
#eval "closedIntervalCompact_iff_complete stated"
#eval "bolzanoWeierstrass_sequentialCompactness stated"

end MiniRealNumbers
