/-
# Measure Theory: Product Constructions

Product sigma-algebras, product measures, and the Fubini-Tonelli theorem
for integrals over product spaces.
-/

import MiniObjectKernel
import MiniMeasureLebesgue.Core.Basic

namespace MiniMeasureLebesgue

/-! ## Product Sigma-Algebra -/

/--
The product sigma-algebra on X × Y is generated by measurable rectangles A × B
where A is measurable in X and B is measurable in Y.
-/
structure ProductSigmaAlgebra (X Y : Type u) (msX : MeasurableSpace X) (msY : MeasurableSpace Y) where
  sigma : SigmaAlgebra (X × Y)
  containsRectangles : ∀ (A : Set X) (B : Set Y),
    isMeasurable msX A → isMeasurable msY B →
    sigma.carrier {p | A p.1 ∧ B p.2}
  minimal : ∀ (S : SigmaAlgebra (X × Y)),
    (∀ (A : Set X) (B : Set Y),
      isMeasurable msX A → isMeasurable msY B →
      S.carrier {p | A p.1 ∧ B p.2}) →
    ∀ (C : Set (X × Y)), sigma.carrier C → S.carrier C

/-- The product sigma-algebra as a measurable space. -/
def productMeasurableSpace (X Y : Type u) (msX : MeasurableSpace X) (msY : MeasurableSpace Y) :
    MeasurableSpace (X × Y) :=
  { sigma := (ProductSigmaAlgebra X Y msX msY).sigma
    space := Set.univ }

/-! ## Product Measure -/

/--
The product measure μ × ν on X × Y is defined by
(μ × ν)(E) = ∫ ν(E_x) dμ(x) = ∫ μ(E^y) dν(y)
where E_x = {y | (x,y) ∈ E} and E^y = {x | (x,y) ∈ E}.
-/
structure ProductMeasure (X Y : Type u)
    (msX : MeasurableSpace X) (msY : MeasurableSpace Y)
    (μ : Measure X msX) (ν : Measure Y msY) where
  measure : Measure (X × Y) (productMeasurableSpace X Y msX msY)
  onRectangles : ∀ (A : Set X) (B : Set Y),
    isMeasurable msX A → isMeasurable msY B →
    measure.value {p | A p.1 ∧ B p.2} = RealNumbers.mul (μ.value A) (ν.value B)

/-- Notation: μ × ν. -/
notation:80 μ:max " ×ₘ " ν:max => ProductMeasure μ ν

/-! ## Fubini-Tonelli Theorem (Statement) -/

/--
Fubini-Tonelli theorem: For a nonnegative measurable function f on X × Y,
the iterated integrals equal the product integral.
-/
def fubiniTonelliStatement (X Y : Type u) (msX : MeasurableSpace X) (msY : MeasurableSpace Y)
    (μ : Measure X msX) (ν : Measure Y msY) : Prop :=
  ∀ (f : (X × Y) → RealNumbers.carrier),
    (∀ p, RealNumbers.le RealNumbers.zero (f p)) →
    True  -- ∫_X×Y f d(μ×ν) = ∫_X (∫_Y f(x,y) dν(y)) dμ(x) = ∫_Y (∫_X f(x,y) dμ(x)) dν(y)

/-- Fubini's theorem for integrable functions (absolute integrability). -/
def fubiniTheoremStatement (X Y : Type u) (msX : MeasurableSpace X) (msY : MeasurableSpace Y)
    (μ : Measure X msX) (ν : Measure Y msY) : Prop :=
  ∀ (f : (X × Y) → RealNumbers.carrier),
    True  -- If ∬ |f| dμdν < ∞, then ∬ f dμdν = ∫∫ f dμ dν = ∫∫ f dν dμ

/-! ## Iterated Integral -/

/--
The iterated integral of f over X then Y.
-/
def iteratedIntegralXY (X Y : Type u) (msX : MeasurableSpace X) (msY : MeasurableSpace Y)
    (μ : Measure X msX) (ν : Measure Y msY)
    (f : (X × Y) → RealNumbers.carrier)
    (hmeas : realMeasurable msX (fun x => lebesgueIntegral msY ν
      (fun y => f (x, y)) (by
        intro c; sorry
      ) (by
        intro y; sorry
      ))) : RealNumbers.carrier :=
  lebesgueIntegral msX μ (fun x => lebesgueIntegral msY ν
    (fun y => f (x, y)) (by
      intro c; sorry
    ) (by
      intro y; sorry
    )) hmeas (by
    intro x; sorry
  )

/-! ## #eval Tests -/

#eval "ProductSigmaAlgebra: generated by measurable rectangles A×B"
#eval "ProductMeasure: (μ×ν)(A×B) = μ(A)·ν(B)"
#eval "Fubini-Tonelli: iterated integrals = product integral"

def sampleRect : Set (Nat × Nat) := {p | p.1 = 0 ∧ p.2 = 1}
#eval "Measurable rectangle: " ++ toString sampleRect

#eval "Fubini statement defined as Prop"

end MiniMeasureLebesgue
