/-
# Real Numbers: Subobjects

Defines subfields of ℝ, dense subfields (ℚ is dense in ℝ), and
the intermediate value property.
-/

import MiniObjectKernel
import MiniRealNumbers.Core.Basic

namespace MiniRealNumbers

/-! ## Subfield -/

/-- A subfield of ℝ: a subset closed under +, *, 0, 1, -, inv. -/
structure Subfield (ℝ : RealNumbers) where
  carrier : Set ℝ.carrier
  zero_mem : ℝ.zero ∈ carrier
  one_mem : ℝ.one ∈ carrier
  add_mem : ∀ {x y}, x ∈ carrier → y ∈ carrier → ℝ.add x y ∈ carrier
  mul_mem : ∀ {x y}, x ∈ carrier → y ∈ carrier → ℝ.mul x y ∈ carrier
  neg_mem : ∀ {x}, x ∈ carrier → ℝ.neg x ∈ carrier
  inv_mem : ∀ {x}, x ∈ carrier → x ≠ ℝ.zero → ℝ.inv x ∈ carrier

/-- The full subfield (all of ℝ). -/
def fullSubfield (ℝ : RealNumbers) : Subfield ℝ where
  carrier := Set.univ
  zero_mem := trivial
  one_mem := trivial
  add_mem := by intro x y hx hy; trivial
  mul_mem := by intro x y hx hy; trivial
  neg_mem := by intro x hx; trivial
  inv_mem := by intro x hx hnz; trivial

/-- Intersection of subfields. -/
def Subfield.inter {ℝ : RealNumbers} (s t : Subfield ℝ) : Subfield ℝ where
  carrier := s.carrier ∩ t.carrier
  zero_mem := ⟨s.zero_mem, t.zero_mem⟩
  one_mem := ⟨s.one_mem, t.one_mem⟩
  add_mem := fun hx hy => ⟨s.add_mem hx.1 hy.1, t.add_mem hx.2 hy.2⟩
  mul_mem := fun hx hy => ⟨s.mul_mem hx.1 hy.1, t.mul_mem hx.2 hy.2⟩
  neg_mem := fun hx => ⟨s.neg_mem hx.1, t.neg_mem hx.2⟩
  inv_mem := by
    intro x hx hnz
    exact ⟨s.inv_mem hx.1 hnz, t.inv_mem hx.2 hnz⟩

/-! ## Dense Subfield -/

/-- A subfield is dense if between any two distinct reals there is
an element of the subfield. -/
def DenseSubfield (ℝ : RealNumbers) (s : Subfield ℝ) : Prop :=
  ∀ x y : ℝ.carrier, ℝ.lt x y → ∃ z ∈ s.carrier, ℝ.lt x z ∧ ℝ.lt z y

/-- The rationals ℚ form a dense subfield of ℝ. -/
theorem rationalsAreDenseSubfield (ℝ : RealNumbers) (harch : ArchimedeanProperty ℝ) :
    ∃ ℚ : Subfield ℝ, DenseSubfield ℝ ℚ := by
  sorry

/-! ## Intermediate Value Property -/

/-- The intermediate value property: if a continuous function on [a,b]
takes values f(a) and f(b), it takes every intermediate value. -/
theorem intermediateValueProperty (ℝ : RealNumbers) (hcomplete : completenessProp ℝ)
    (f : ℝ.carrier → ℝ.carrier) (a b : ℝ.carrier)
    (hcont : ∀ x y ε, ℝ.lt ℝ.zero ε → ℝ.lt x y → ?_) -- continuity condition
    : ∀ y : ℝ.carrier, ℝ.le (f a) y → ℝ.le y (f b) →
      ∃ c : ℝ.carrier, ℝ.le a c ∧ ℝ.le c b ∧ f c = y := by
  sorry

/-! ## Subfield Generated by a Set -/

/-- The subfield generated by a set: the smallest subfield containing S. -/
def generatedSubfield (ℝ : RealNumbers) (S : Set ℝ.carrier) : Subfield ℝ :=
  fullSubfield ℝ  -- place holder: actual construction uses intersection
  -- Would be: intersection of all subfields containing S

/-! ## #eval Tests -/

#eval "Subfield defined"
#eval "fullSubfield defined"
#eval "DenseSubfield defined"
#eval "intermediateValueProperty stated"
#eval "generatedSubfield defined"

end MiniRealNumbers
