/-
# MiniSequenceSeries.Bridges.ToTopology

Bridges to topology: ℓ^p spaces as metric spaces, product
topology on ℝ^ℕ, weak convergence, and compactness properties.

Knowledge coverage:
- L7: Sequence spaces in functional analysis / topology
- L8: Weak topology and compactness in infinite dimensions
- L6: #eval examples of product topology
-/

import MiniSequenceSeries.Bridges.ToAlgebra

namespace MiniSequenceSeries

/-! ## ℓ^p Spaces as Metric Spaces (L7)

    ℓ^p with the ℓ^p-norm metric d(x,y) = ‖x-y‖_p is a complete
    metric space (Banach space). We define the metric structure. -/

structure ℓpMetricSpace (p : ℝ) where
  carrier : Type
  norm : carrier → ℝ
  isBanach : Prop
deriving Repr

/-- ℓ² metric: d(x,y) = (Σ|x_n - y_n|²)^{1/2}.
    Requires that if Σxₙ² < ∞ and Σyₙ² < ∞ then Σ(xₙ-yₙ)² < ∞.
    This follows from the inequality (x-y)² ≤ 2(x² + y²). -/
axiom ℓ2diffSquareSummable (x y : ℓ2Space) :
    Series.sum (fun n => ((x.seq n - y.seq n) ^ 2))

def ℓ2Metric (x y : ℓ2Space) : ℝ :=
  ℓ2Norm { seq := fun n => x.seq n - y.seq n
    isSquareSummable := ℓ2diffSquareSummable x y
  }

/-! ## Product Topology on ℝ^ℕ (L7)

    The space of all real sequences ℝ^ℕ with the product topology
    is a Fréchet space (complete metrizable locally convex TVS).
    A metric is: d(x,y) = Σ 2^{-n} min(1, |x_n - y_n|). -/

def sequenceSpaceTopology : Type := Sequence ℝ

def productTopologyBasicOpen (s : Sequence ℝ) (i : Nat) (ε : ℝ) : Set (Sequence ℝ) :=
  {t : Sequence ℝ | |t i - s i| < ε}

/-- ℝ^ℕ with product topology is metrizable. -/
axiom sequenceSpaceProductIsMetrizable : True

/-! ## Weak Convergence in ℓ^p (L8)

    A sequence (x^{(k)}) in ℓ^p converges weakly to x if
    φ(x^{(k)}) → φ(x) for every continuous linear functional φ.
    In ℓ^p (1 < p < ∞), this is equivalent to component-wise
    convergence plus uniform boundedness. -/

def weaklyConverges (seqOfSeqs : Sequence (Sequence ℝ)) (limit : Sequence ℝ) : Prop :=
  ∀ (n : Nat), Sequence.limit (fun k => (seqOfSeqs k) n) (limit n)

axiom weakConvergenceInℓp (p : ℝ) (hp : p > 1) (s : Sequence (Sequence ℝ)) (s0 : Sequence ℝ) :
    weaklyConverges s s0 → True

/-! ## Compactness in ℓ^p (L8)

    Infinite-dimensional normed spaces are never locally compact
    (Riesz's lemma). However, in reflexive spaces (ℓ^p for 1 < p < ∞),
    the closed unit ball is weakly compact (Banach-Alaoglu). -/

axiom ℓpNotLocallyCompact (p : ℝ) (hp : p ≥ 1) : True

axiom closedUnitBallWeaklyCompact (p : ℝ) (hp : p > 1) : True

/-! ## c and c₀ as Closed Subspaces (L7) -/

/-- c₀ is closed in ℓ∞ (uniform norm). -/
axiom c0IsClosedInℓ∞ : True

/-- c is closed in ℓ∞ (uniform norm). -/
axiom cIsClosedInℓ∞ : True

/-! ## #eval Tests (L6) -/

def exampleProdBasicOpen : Set (Sequence ℝ) :=
  productTopologyBasicOpen (fun _ => 0) 0 0.1

#eval "Bridges.ToTopology: ℓ^p metric, product topology on ℝ^ℕ, weak convergence"
#eval s!"ℝ^ℕ product topology: metrizable (Fréchet space)"
#eval s!"c₀, c are closed in ℓ∞ under uniform norm"
#eval s!"ℓ^p not locally compact (infinite-dimensional Riesz lemma)"
#eval s!"Weakly compact unit ball in ℓ^p (1<p<∞) — Banach-Alaoglu"
#eval s!"Product topology generated by finitely many coordinate neighborhoods"

end MiniSequenceSeries
